services:
  pgbackend:
    container_name: pgbackend
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - pgbackend_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped

  backend:
    container_name: backend
    build: ./src/backend
    volumes:
      - backend_data:/var/www/html/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - pgbackend

  nginx:
    container_name: nginx
    build: ./src/nginx
    volumes:
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /var/www/42ecole/src/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443   # For HTTP
      - 80:80   # For HTTPS
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  pgbackend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/42ecole/data/pgadmin
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/42ecole/data/backend